version: "3"

services:
  nest:
    depends_on:
      - db
    networks:
      - net
    build: .
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./:/workspace
    restart: always
  db:
    image: mysql:8.0
    networks:
      - net
    ports:
      - "3306:3306"
    volumes:
      - dbvol:/var/lib/mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user

networks:
  net:

volumes:
  dbvol:
